language: java 

env:
  global:
    - CODECOV_TOKEN="b38dd081-ea40-445a-82cd-798aace195a6"

before_script:
  - mvn install -Djacoco.skip -DskipTests=true -Dmaven.javadoc.skip=true -B -V 

script: mvn test -B 

after_success:
  - bash <(curl -s https://codecov.io/bash)
